server:
  port: 8763 #网关项目端口号
spring:
  application:
    name: kentra-cms-gateway #网关项目名称
  security:
    user:
      name: "admin"
      password: "123456"
  servlet:
    multipart:
      enabled: true
      max-file-size: 20MB
      max-request-size: 200MB